name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  CI: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: npm ci
    - name: lint js
      run: npm run lint:js
    - name: lint hbs
      run: npm run lint:hbs
    - name: lint style
      run: npm run lint:style
    - name: test
      run: npm run test:ember

#  test-floating:
#    name: Floating Dependencies
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/setup-node@v1
#      with:
#        node-version: 14
#    - name: install dependencies
#      run: npm install --no-package-lock
#    - name: test
#      run: npm run test:ember

  test-embroider:
    name: ember-try
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ember-try-scenario:
         - embroider-safe
         - embroider-optimized
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: install dependencies
      run: npm ci
    - name: test
      env:
        EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
      continue-on-error: true
      run: node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
