name: Tag Version

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Semver Release Type (major,minor,patch)'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.ZORGBORT_TOKEN }}
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm
    - name: Validate releaseType
      run: npx in-string-list ${{ github.event.inputs.releaseType }} major,minor,patch
    - name: Setup Git
      run: |
        git config user.name Zorgbort
        git config user.email info@iliosproject.org
    - name: Increment Version
      run: pnpm version ${{ github.event.inputs.releaseType }}
    - name: Push Changes
      run: git push --follow-tags
